apiVersion: v1
kind: Service
metadata:
  labels:
    app: mydeployment
  name: mydeployment
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: mydeployment
  type: NodePort

