apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysvc
  name: mysvc
spec:
  ports:
  - name: 80-80
    nodePort: 30009
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: mysvc
  type: NodePort

