apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: busybox    
    args: ["/bin/sh", "-c","echo $(base64 -d /etc/secret-volume/password)" ]
    volumeMounts:
    - name: secret-volume
      readOnly: false
      mountPath: "/etc/secret-volume"
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
  volumes:
  - name: secret-volume
    secret:
      secretName: mysecret
